sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.3"
install:
  - python setup.py install
  - pip install codecov
script:
  - coverage run --source=flask_misaka setup.py test
after_success:
  - codecov
