language: python
python:
  - "2.7"
  - "3.3"
install:
  - python setup.py install
  - pip install coverage coveralls --use-mirrors
script:
  - coverage run --source=flask_misaka setup.py test
after_success:
  - coveralls
